services:
  multas-front-staging:
    container_name: multas-front-staging
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4203:80"
    networks:
      - multas_network
    labels:
      - com.multas.environment=staging
    environment:
      - API_URL=${API_URL}

networks:
  multas_network:
    external: true
