services:
  multas-front-dev:
    container_name: multas-front-dev
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4200:80"
    networks:
      - multas_network
    labels:
      - com.multas.environment=dev
    environment:
      - API_URL=${API_URL}

networks:
  multas_network:
    external: true
